### ISSUE TITLE
Can't see all groups on a small screen

### ISSUE THREAD

**Issue by deanishe** [passiomatic/coldsweat#113]
The "groups" popup and the main menu itself are not scrollable. As a result, if you have more groups than fit on your screen, it's impossible to see or select them.

I can only see about half of my groups on my notebook (Safari 10.1.1), and even fewer on my phone (iOS 10.3.2).

Could you make it possible to scroll the groups list?

Ideally—for me at least—make the groups list a separate column that can be left open instead of disappearing every time you click on a group.

**Comment by passiomatic** [comment]
Yes, this is inconvenient if you have many groups. 

One solution would be to create a new main column view listing all groups, just like feeds and entries. It's a all-or-nothing approach but would be make them bookmark-able, too.  

An intermediate solution: present the most 5 bigger groups  in the popup, ending with "View all groups" menu item linked the main column groups view.
