### ISSUE TITLE
Is this still being developed?

### ISSUE THREAD

**Issue by a3rosol** [passiomatic/coldsweat#114]
Thinking about using this software, but the last commit was a year ago. Is this still being developed?

**Comment by passiomatic** [comment]
Hi there. I'm rewriting the frontend from scratch. The rationale is that to improve the UI and fix current issues I have to jumping thru hoops which complicate code and this in the end it does not pay off.  This will take a while, probably a few weeks. 

In the meantime if you feel that the current Coldsweat features satisfy your needs I suggest you  to give it a try.

**Comment by a3rosol** [comment]
I gave it a try and it works well 😊 however, I'm wondering how the "grouping similar items" feature works. Do I have to activate it somewhere? Does it only work with english articles? Does it work with Reeder (ios/Mac)?

**Comment by passiomatic** [comment]
I'm not sure what does you mean by "grouping similar items". Do you mean feed groups?

**Comment by a3rosol** [comment]
No, I meant grouping similar news topics. For example: some major news event happens (iphone release). 7 different sites that I subscribed to start spewing out 50 articles every hour. Can these articles be grouped together, so I don't see 50 articles but rather 10 articles? Like google news style topic aggregation. Maybe group them via the Hot/Fever api?

**Comment by passiomatic** [comment]
Unfortunately there's nothing like Fever's "Hot links" right now. The feature is tracked here: https://github.com/passiomatic/coldsweat/issues/68
