### ISSUE TITLE
Feeds deactivated because error "not modified"

### ISSUE THREAD

**Issue by a3rosol** [passiomatic/coldsweat#116]
![Image](https://i.imgur.com/qjaRmgN.jpg)

This happens way to often. A lot of my feeds get deactivated regularly because of this "error". But is this an error though? Technically, 302 is not an error code

**Comment by passiomatic** [comment]
I see it too. I believe it's not the "not modified" (which indeed is not an error) to increase the error count  and thus causing the feed to be disabled, but the last HTTP error returned by the server which is not recorded correctly by the fetcher.  

Actually the fetcher here is trying to be too clever, which makes the code hard to reason about. I need to simplify the whole process. 

**A workaround**

As a temporary measure you may want to set to `0` the config `max_errors` setting, which makes Coldsweat to ignore the fetching errors.
