### ISSUE TITLE
Videos are removed from feed entries

### ISSUE THREAD

**Issue by Pablo2m** [passiomatic/coldsweat#75]
Currently youtube videos do not appear

I think it is not bad, but it would be nice to choose from:
- Not see the videos
- Display a link to youtube
- View the embedded video

**Comment by passiomatic** [comment]
I've managed to implement this feature in 5738caeda8d5060cbd5260c2856d9d95d9c74eff. At the moment the only allowed domains as sources for iframe videos  are: 
```
www.youtube.com
www.youtube-nocookie.com
player.vimeo.com
```
It would be good to have a more precise list. 

**Note**: this commit doesn't fix the YT-generated RSS feeds. Currently the YT feeds do not contain embeds but only a thumbnail image and a _link_ to the of the video. This will be handled in another way in the future UI.
