### ISSUE TITLE
`python sweat.py setup` should be scriptable

### ISSUE THREAD

**Issue by SkyCrawl** [passiomatic/coldsweat#78]
**The problem**
I'm currently making a QPKG application for coldsweat and have run into a scripting issue with the `python sweat.py setup` command - passwords are **not** read from the standard input I provide (email **is**).
Speaking with code, trying to feed email, password and password again to it:
```
python sweat.py setup <<EOF
nevermind@nevermind.test
coldsweat
coldsweat
EOF
```
hangs at the first password request because `getpass` doesn't read from standard input that is not a terminal, apparently by design.

**The solution**
Coming shortly in a PR.

**Comment by passiomatic** [comment]
I've merged your code into the rafactored commands.py module. Thank you for your contribution!
