### ISSUE TITLE
Support password-protected feeds

### ISSUE THREAD

**Issue by tewe** [passiomatic/coldsweat#81]
Feeds using basic auth already work if you put them directly into the database:

    https://myname:mypass@www.domain.com/myfeed

To make the web interface work `utilities.is_valid_url` needs adjusting.

**Comment by passiomatic** [comment]
Yeah, current regexp doesn't take into account the user:pass bit.  Also the discussion here is interesting: http://stackoverflow.com/questions/827557/how-do-you-validate-a-url-with-a-regular-expression-in-python

The current Django URL implementation is a monster.  With Coldsweat validator I was after to  catch the most obvious malformed URL's. 

Care to expand the current regexp to include auth information?

**Comment by tewe** [comment]
I can't test with IPv6. Would the rest of the code even work with http://[0:ab:cd]/feed?

**Comment by passiomatic** [comment]
No need to include support for IPv6, I was referring your willingness to edit the regexp to include the user:password bit.    :)

**Comment by tewe** [comment]
I like to do things right. Oh well, just make this the second line:

        r'(?:[^:@]+:[^:@]+@)?'  # credentials
