### ISSUE TITLE
Store hashed passwords into database

### ISSUE THREAD

**Issue by passiomatic** [passiomatic/coldsweat#85]
Store salted and hashed password and Fever apikey into database. 

See: 
- http://blog.codinghorror.com/your-password-is-too-damn-short/
- https://docs.python.org/2/library/hashlib.html#hashlib.pbkdf2_hmac

Since different algorithms can be available on a user platform Coldsweat could store salted passwords with a prefix specifying  the algorithm used, something like: 

sha1:cc4a5ce1b3df48aec5d22d1f16b894a0b894eccc

**Comment by passiomatic** [comment]
Changed my mind: let use new Peewee's PasswordField instead: http://docs.peewee-orm.com/en/latest/peewee/playhouse.html?highlight=passwordfield#PasswordField

We need to add a `bcrypt` dependency but it solves a few potential issues while dealing with the availability of different algorithms on different platforms.

**Comment by oz123** [comment]
Peewee in version 3 dropped password field, but it's not complected to implement similar good logic. Passlib has good examples.

**Comment by passiomatic** [comment]
Done while porting codebase to Python 3 [583bd5c](https://github.com/passiomatic/coldsweat/commit/583bd5c82cb66804a76d954f9b92fd0447c9f0ed)
