### ISSUE TITLE
Socket connection URL for postgresql

### ISSUE THREAD

**Issue by abyth** [passiomatic/coldsweat#90]
The current connection URL approach has parsing issues when trying to connect to a PostgreSQL Server via Unix Domain Socket, because the host and database name are not separable ('/')

**Comment by passiomatic** [comment]
Could you give me an example? Thanks.

**Comment by abyth** [comment]
With the old configuration scheme this worked:
hostname: /home/username/tmp
username: username
password: pw
database: coldsweat
The URL would look like this:
postgresql://username:pw@/home/username/tmp/coldsweat

**Comment by passiomatic** [comment]
I see. Damn, I didn't think about the socket approach before ditching the connection parameters. Coldsweat _could_ check for connection_url and then hostname/username/password/database options.  Of course this defeats the purpose of the connection_url parameter, that is, simplify the code and configuration phase.

The other, painful way, is to maintain your branch of Coldsweat with the old connection method.
