### ISSUE TITLE
Reset password

### ISSUE THREAD

**Issue by yuvallanger** [passiomatic/coldsweat#97]
I want to be able to reset my user password through the sweat.py command.

Many thanks,
Yuval Langer.

**Comment by passiomatic** [comment]
I guess you are "locked out"  the web UI since you don't remember the password, don't you?  

Cause you can change your password via the "profile" modal dialog.

**Comment by yuvallanger** [comment]
What is that?

**Comment by passiomatic** [comment]
See attached screenshots: 

![screen shot 2016-02-14 at 19 01 11](https://cloud.githubusercontent.com/assets/56371/13035333/c90641e6-d34d-11e5-9c3f-383083cc68bf.png)
![screen shot 2016-02-14 at 19 01 18](https://cloud.githubusercontent.com/assets/56371/13035334/cb65c074-d34d-11e5-93c7-36c908a4ee3a.png)

**Comment by yuvallanger** [comment]
I am not logged to my coldsweat account. Reaching the password change form
is not possible for me without the password.

**Comment by passiomatic** [comment]
"Reaching the password change form is not possible for me without the password."

Indeed, you are right. Actually there's no way to reset a password in a clean way. Of course you can change the password by accessing the database directly (with SQLite I use this Firefox extension https://addons.mozilla.org/it/firefox/addon/sqlite-manager/, with MySQL you have many more choices).

Like you have suggested in the future there could be a reset command or perhaps a -p (--password) option for the setup command.

**Comment by passiomatic** [comment]
FYI: version 0.9.6 allows you to reset a user password with the `setup` -w option.
